import requests
import json

def test():
    req = {
        "repo_url": "https://github.com/welldone-software/why-did-you-render",
        "issue_number": 290
    }
    # Call the backend
    try:
        r = requests.post("http://localhost:8003/api/re-analyze-issue", json=req, timeout=300)
        print("Status code:", r.status_code)
        data = r.json()
        briefing = data.get("agent3_output", {}).get("briefing_markdown", "")
        print("BRIEFING RAW STRING START: ===>")
        print(repr(briefing[:1000]))
        print("<=== BRIEFING RAW STRING END")
        
        # Look for hashes in the briefing
        if "#" in briefing:
            print("SUCCESS: Hashes found in the raw string.")
        else:
            print("FAILURE: No hashes found in the string generated by backend.")
    except Exception as e:
        print("Error:", e)

if __name__ == "__main__":
    test()
